apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drone
  namespace: drone
  annotations:
    kubernetes.io/ingress.global-static-ip-name: drone-static-ip
spec:
  backend:
    serviceName: drone-service
    servicePort: 8000

