apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:0.8.5
          ports:
            - containerPort: 8000
            - containerPort: 9000
          env:
            - name: DRONE_OPEN
              value: "false"
            - name: DRONE_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_ADMIN
            - name: DRONE_HOST
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_HOST
            - name: DRONE_GITHUB
              value: "true"
            - name: DRONE_GITHUB_URL
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_GITHUB_URL
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_CLIENT
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_SECRET
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_SECRET
            - name: DRONE_GITHUB_PRIVATE_MODE
              value: "true"
            - name: DRONE_DATABASE_DRIVER
              value: "mysql"
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_DATABASE_DATASOURCE
            - name: DRONE_DEBUG
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/drone
              name: drone-home

        # https://github.com/GoogleCloudPlatform/kubernetes-engine-samples/blob/master/cloudsql/mysql_wordpress_deployment.yaml#L39
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          env:
            - name: DRONE_DB_CONN_NAME
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_DB_CONN_NAME
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=prj-gcp:asia-east1:drone-db=tcp:3306",
                    "-credential_file=/secrets/cloudsql/CLOUDSQL_CREDENTIALS"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true

      # volumes:
      #   - name: drone-home
      #     hostPath:
      #       path: /var/lib/drone
      # volumes:
      #   - name: drone-home
      #     emptyDir: {}
      #
      # volumes:
      #   - name: drone-home
      #     gcePersistentDisk:
      #       pdName: drone-home
      #       fsType: ext4
      #
      volumes:
        - name: drone-home
          persistentVolumeClaim:
            claimName: drone-volume-claim

        - name: cloudsql-instance-credentials
          secret:
            secretName: drone-secrets
