apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        # Drone
        - name: drone-server
          image: drone/drone:0.8.5
          ports:
            - containerPort: 8000
            - containerPort: 9000
          envFrom:
            # configmap/secretを全て環境変数に展開される
            - configMapRef:
                name: drone-config-map
            - secretRef:
                name: drone-secrets
          volumeMounts:
            - mountPath: /var/lib/drone
              name: drone-home

        # CloudSQL
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          env:
            - name: DRONE_DB_CONN_NAME
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_DB_CONN_NAME
          command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=prj-gcp:asia-east1:drone-db=tcp:3306",
                    "-credential_file=/secrets/cloudsql/CLOUDSQL_CREDENTIALS"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:
        - name: drone-home
          persistentVolumeClaim:
            claimName: drone-volume-claim

        - name: cloudsql-instance-credentials
          secret:
            secretName: drone-secrets
