apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:0.8
          ports:
            - containerPort: 8000
            - containerPort: 9000
          env:
            - name: DRONE_OPEN
              value: "true"
            - name: DRONE_ORGS
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_ORGS
            - name: DRONE_HOST
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_HOST
            - name: DRONE_GITHUB
              value: "true"
            - name: DRONE_GITHUB_URL
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_GITHUB_URL
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_CLIENT
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_SECRET
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_SECRET
            - name: DRONE_GITHUB_PRIVATE_MODE
              value: "true"
            - name: DRONE_DATABASE_DRIVER
              value: "mysql"
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_DATABASE_DATASOURCE
          volumeMounts:
            - mountPath: /var/lib/drone
              name: drone-home
      # volumes:
      #   - name: drone-home
      #     hostPath:
      #       path: /var/lib/drone
      # volumes:
      #   - name: drone-home
      #     emptyDir: {}
      #
      # volumes:
      #   - name: drone-home
      #     gcePersistentDisk:
      #       pdName: drone-home
      #       fsType: ext4
      #
      volumes:
        - name: drone-home
          persistentVolumeClaim:
            claimName: drone-volume-claim
