apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config-map
  namespace: drone
data:
  DRONE_OPEN: "false"
  DRONE_GITHUB: "true"
  DRONE_GITHUB_URL: ${DRONE_GITHUB_URL}
  DRONE_HOST: ${DRONE_HOST}
  DRONE_ORGS: ${DRONE_ORGS}
  DRONE_ADMIN: ${DRONE_ADMIN}
  DRONE_DB_CONN_NAME: ${DRONE_DB_CONN_NAME}
  DRONE_GITHUB_PRIVATE_MODE: "true"
  DRONE_DATABASE_DRIVER: "mysql"
  DRONE_DEBUG: "true"
