apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config-map
  namespace: drone
data:
  DRONE_GITHUB_URL: ${DRONE_GITHUB_URL}
  DRONE_HOST: ${DRONE_HOST}
  DRONE_ORGS: ${DRONE_ORGS}
  DRONE_ADMIN: ${DRONE_ADMIN}
  DRONE_DB_CONN_NAME: ${DRONE_DB_CONN_NAME}
