apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
  namespace: drone
type: Opaque
data:
  DRONE_GITHUB_CLIENT: ${DRONE_GITHUB_CLIENT_BASE64}
  DRONE_GITHUB_SECRET: ${DRONE_GITHUB_SECRET_BASE64}
  DRONE_SECRET: ${DRONE_SECRET_BASE64}
