apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drone-server
  namespace: drone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drone-server
    spec:
      containers:
        - name: drone-server
          image: drone/drone:0.8
          ports:
            - containerPort: 8000
            - containerPort: 9000
          env:
            - name: DRONE_OPEN
              value: "true"
            - name: DRONE_HOST
              value: "http://35.190.49.235"
            - name: DRONE_GITHUB
              value: "true"
            - name: DRONE_GITHUB_URL
              valueFrom:
                configMapKeyRef:
                  name: drone-config-map
                  key: DRONE_GITHUB_URL
            - name: DRONE_GITHUB_CLIENT
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_CLIENT
            - name: DRONE_GITHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_GITHUB_SECRET
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: DRONE_SECRET
            - name: DRONE_GITHUB_PRIVATE_MODE
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/drone
              name: drone-home
      volumes:
        - name: drone-home
          emptyDir: {}
      # volumes:
      #   - name: drone-home
      #     gcePersistentDisk:
      #       pdName: drone-home
      #       fsType: ext4
      #       # partition: 1
