apiVersion: v1
kind: Service
metadata:
  name: drone-service
  namespace: drone
spec:
  type: NodePort
  # type: LoadBalancer
  selector:
    app: drone-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
