apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker
  namespace: drone
  labels:
    app: docker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - image: docker:dind
          name: docker
          volumeMounts:
            - name: docker-storage
              mountPath: /var/lib/docker
          securityContext:
            privileged: true
      volumes:
        - name: docker-storage
          emptyDir: {}
