apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-volume
  namespace: drone
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: drone-disk
    fsType: ext4
